### ISSUE TITLE
请问上传的代码中有其他方法的代码吗，那是怎么比较的

### ISSUE THREAD

**Issue by zycc853** [icoz69/CEC-CVPR2021#1]

**Comment by Nan-S** [comment]
你需要什么方法的？

**Comment by zycc853** [comment]
如果可以的化，都想了解一下



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月6日(星期二) 上午10:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [icoz69/CEC-CVPR2021] 请问上传的代码中有其他方法的代码吗，那是怎么比较的 (#1)





 
你需要什么方法的？

**Comment by Nan-S** [comment]
TOPIC的我们直接follow他们论文里的结果，你可以参考他们的代码https://github.com/xyutao/fscil
DeepEMD你可以参考https://github.com/icoz69/DeepEMD
cosine我放在models/base里了

**Comment by zycc853** [comment]
好的，那请问base中只有cosine这一种方法是不，就相当于你的论文代码实现了一种，再复现了一种，其他是直接follow过来的吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月6日(星期二) 上午10:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [icoz69/CEC-CVPR2021] 请问上传的代码中有其他方法的代码吗，那是怎么比较的 (#1)





 
TOPIC的我们直接follow他们论文里的结果，你可以参考他们的代码https://github.com/xyutao/fscil，DeepEMD你可以参考https://github.com/icoz69/DeepEMD，cosine我放在models/base里了

**Comment by Nan-S** [comment]
哦不是的，可以参考一下我们的train.py里关于不同training mode的选择和组合，base中还有linear classifier的选择，TOPIC里follow了哪些数据可以仔细读一下paper里关于和SOTA对比那一部分

**Comment by zycc853** [comment]
好的，谢谢您的回复。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月6日(星期二) 中午11:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [icoz69/CEC-CVPR2021] 请问上传的代码中有其他方法的代码吗，那是怎么比较的 (#1)





 
哦不是的，可以参考一下我们的train.py里关于不同training mode的选择和组合，base中还有linear classifier的选择，TOPIC里follow了哪些数据可以仔细读一下paper里关于和SOTA对比那一部分

**Comment by chester-w-xie** [comment]
> TOPIC的我们直接follow他们论文里的结果，你可以参考他们的代码https://github.com/xyutao/fscil DeepEMD你可以参考https://github.com/icoz69/DeepEMD cosine我放在models/base里了

TOPIC 的代码不完整，根本跑不通呢，肿么办呢，

**Comment by SwaggyZhang** [comment]
> 

作者的意思应该是直接参照了TOPIC的论文结果，并没有自己复现TOPIC的代码
