### ISSUE TITLE
Hello, I would like to ask you for advice on the following questions.

### ISSUE THREAD

**Issue by tangdouer** [icoz69/CEC-CVPR2021#10]
Hello, I would like to ask you for advice on the following questions.
1. I can't find the code location to implement this part in the code. Is it convenient to tell.
We first compute a relation coefficient between the node j and all nodes in the graph.
2. Is the graph structure realized through the FC layer?

**Comment by Nan-S** [comment]
Hi,
Thanks for your question and sorry for the late reply.
1. The implementation of the mentioned part in the code is at models/cec/Network.py line 61.
2. Yes, we use FC layer weights as the nodes in the graph model. You can refer to section 4.2 in the paper.
