### ISSUE TITLE
Confusion on freezing backbone

### ISSUE THREAD

**Issue by solangii** [icoz69/CEC-CVPR2021#12]
Hello,
First of all, thank you for your great work!

During understanding the code and paper, I have a confusion about the point of freezing the backbone. If the workflow of the process is: a)pre-training stage, b)pseudo-incremental learning stage, and c)classifier learning and adaptation stage, which one is right? :

> 1. After the pre-training stage, the backbone model is freezing
> 2. After the pseudo-incremental learning stage, the backbone model is freezing

I am confused because it seems to be `1` according to Figure 2 in the paper. 
learnable params in the pseudo-incremental learning stage don't have model R(backbone). 
![aa](https://raw.githubusercontent.com/icoz69/CEC-CVPR2021/main/pipeline.png)

However, according to the code, in the pseudo-incremental learning stage, the encoder is one of the learnable params. The encoder parameters are included in the optimizer. So it seems to be `2`. 
https://github.com/icoz69/CEC-CVPR2021/blob/3a5d335f19349aa2e5fa75c88aa2c701b6e5513d/models/cec/fscil_trainer.py#L142

That is why I'm confused about where the backbone model is freezing. I would appreciate it if you could let me know which one is right, `1` or `2`.
And if there's something I misunderstood, please let me know. Thank you.

**Comment by Nan-S** [comment]
Hi,
Thanks for your question. Sorry for the late reply.
The point of freezing backbone is `2`, we later found that slightly finetune encoder is also helpful during pseudo-incremental learning stage.
