### ISSUE TITLE
visualization of t-sne

### ISSUE THREAD

**Issue by JulieCarlon** [icoz69/CEC-CVPR2021#13]
Could you tell me how to visualize the decision boundary and data as Figure4 shows using t-sne? Looking forward to your reply.

**Comment by ghost** [comment]
I would also like to know, how you visualized the decision boundaries in Figure 4?

**Comment by Nan-S** [comment]
The basic idea is to sample lots of points in the background area and classify them according to the distance to the prototypes and then plot different class points in different colors.
