### ISSUE TITLE
Is the code missing the pre-training part?

### ISSUE THREAD

**Issue by chester-w-xie** [icoz69/CEC-CVPR2021#14]
Hi, Thank you for your wonderful work!
You describe in your article that the first stage of the method is to use the training data from session 0 to pre-train the backbone so that it has some feature extraction capability. However, in your code, the pre-trained model you provided on Google Drive is loaded directly by default. I tried to run the code without loading the pre-trained model and got poor results.
 So, could you possibly share how you are doing in the first stage of pre-training? 
Or, it would be great if you could add the code for the pre-training stage, thank you very much!

**Comment by Nan-S** [comment]
Model/base is the pre-training part.  You can use the 'Pretrain scripts' provided in README to run the first stage of pre-training. Same answer for #15 
I will proceed to close both of them.
