### ISSUE TITLE
About the mini_imagenet datasets

### ISSUE THREAD

**Issue by HarborYuan** [icoz69/CEC-CVPR2021#18]
Hi @icoz69 @Nan-S ,

Thanks for your great work CEC.

I am trying to follow your paper but I found that I cannot find the original images of the mini_imagenet dataset downloaded from the google drive link in this repo.
Based on my understanding, the mini_imagenet dataset is originally created by [Ravi et al. ](https://github.com/twitter-research/meta-learning-lstm/tree/master/data/miniImagenet). For example, n0153282900000005.jpg,n01532829 means the no.5 image of the imagenet train split.

n01532829
|---n01532829_3.JPEG
|---n01532829_6.JPEG
| ---n01532829_26.JPEG
| ---n01532829_27.JPEG
| ---n01532829_28.JPEG (this one)

However, I cannot find the miniimagenet/images/n0153282900000005.jpg image (in the zipped file) from the original imagenet dataset (by file hash search).
![miniimagenet/images/n0153282900000005.jpg](https://user-images.githubusercontent.com/25056573/184540041-6cd312df-2a41-47a1-8765-b6c8f365de41.jpg)

May I ask how to create the mini imagenet dataset from scratch?

Thanks again

**Comment by Nan-S** [comment]
Please double-check if you use the correct original imagenet dataset. We use the same miniimagenet dataset as TOPIC.

**Comment by HarborYuan** [comment]
Thanka for your help. @Nan-S 

I can confirm that I use the correct original imagenet dataset.
Is the method I mentioned above (choose n01532829_28.JPEG) the correct way to extract images from the original imagenet dataset?
Or I'd better download the preprocessed mini_imagenet dataset package.

**Comment by Nan-S** [comment]
I didn't create the dataset myself. I am not sure if you are using the correct way or not. The dataset provided was also downloaded from other few-shot learning projects. I would suggest you download the mini_imagenet dataset provided.
