### ISSUE TITLE
Number of Nodes in CUB200 based Pre-trained model

### ISSUE THREAD

**Issue by TouqeerAhmad** [icoz69/CEC-CVPR2021#6]
Hi, Thank you for making your code public!
I have a question about the pre-trained model specifically one with CUB200 dataset. Whether the model you are sharing 'session0_max_acc7552_cos.pth' is the model after all the sessions have passed or just after the base session. As I was looking at the architecture and the fc layer has 200 nodes (module.fc.weight: torch.Size([200, 512])), whereas after session 0 there should only be 100 nodes. On the other hand, the name of the model suggest session0. 
Please advise. 
Thanks, 
Touqeer

**Comment by icoz69** [comment]
hi
thank you for your interest in our work. for implementation convenience, we initialize the fc for all coming classes at the beginning but only use the corresponding ones in each session. and thanks for the suggestions.

**Comment by TouqeerAhmad** [comment]
Thank you so very much for the prompt reply! Just to confirm the pre-trained model you provided is just after session0. 

I also have another question, I assume in each case the ResNet18 being used is pre-trained on ImageNet-2012 -- same as that of FSCIL paper?

**Comment by icoz69** [comment]
Only models for CUB200 are imagenet pre-trained.
