### ISSUE TITLE
Does GAT participate the adaptation stage?

### ISSUE THREAD

**Issue by wonda** [icoz69/CEC-CVPR2021#7]
Hi, Thanks for your great work!
I have a question about the GAT module. I notice that, in your implementation, the attention module only participates the pseudo-incremental learning stage (session == 0). But in the paper, it seems that GAT is used in adaptation stage (session > 0) to generate the weights of classifier. 
I really appreciate any help you can provide. Thanks!

**Comment by Nan-S** [comment]
Hi wonda,
The GTA module is used in the adaptation stage.  You can refer to models/cec/fscil_trainer.py L256 and L379. GAT is in the _forward function to get the after adaptation weights for the further classification.
https://github.com/icoz69/CEC-CVPR2021/blob/3a5d335f19349aa2e5fa75c88aa2c701b6e5513d/models/cec/fscil_trainer.py#L379

**Comment by JulieCarlon** [comment]
but the parameters will not be updated, right? All the parameters is fixed between 'cec' stage and the GAT is used to compute the attention and classification.
